/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PatriotPledgeNFTV9 {
  export type CampaignViewStruct = {
    id: BigNumberish;
    category: string;
    baseURI: string;
    goalNative: BigNumberish;
    goalUsd: BigNumberish;
    grossRaised: BigNumberish;
    netRaised: BigNumberish;
    giftsReceived: BigNumberish;
    editionsMinted: BigNumberish;
    maxEditions: BigNumberish;
    priceNative: BigNumberish;
    priceUsd: BigNumberish;
    nonprofit: AddressLike;
    submitter: AddressLike;
    active: boolean;
    paused: boolean;
    closed: boolean;
    refunded: boolean;
    immediatePayoutEnabled: boolean;
  };

  export type CampaignViewStructOutput = [
    id: bigint,
    category: string,
    baseURI: string,
    goalNative: bigint,
    goalUsd: bigint,
    grossRaised: bigint,
    netRaised: bigint,
    giftsReceived: bigint,
    editionsMinted: bigint,
    maxEditions: bigint,
    priceNative: bigint,
    priceUsd: bigint,
    nonprofit: string,
    submitter: string,
    active: boolean,
    paused: boolean,
    closed: boolean,
    refunded: boolean,
    immediatePayoutEnabled: boolean
  ] & {
    id: bigint;
    category: string;
    baseURI: string;
    goalNative: bigint;
    goalUsd: bigint;
    grossRaised: bigint;
    netRaised: bigint;
    giftsReceived: bigint;
    editionsMinted: bigint;
    maxEditions: bigint;
    priceNative: bigint;
    priceUsd: bigint;
    nonprofit: string;
    submitter: string;
    active: boolean;
    paused: boolean;
    closed: boolean;
    refunded: boolean;
    immediatePayoutEnabled: boolean;
  };

  export type GiftStruct = {
    donor: AddressLike;
    amount: BigNumberish;
    platformFee: BigNumberish;
    nonprofitFee: BigNumberish;
    netAmount: BigNumberish;
    timestamp: BigNumberish;
    displayName: string;
    message: string;
  };

  export type GiftStructOutput = [
    donor: string,
    amount: bigint,
    platformFee: bigint,
    nonprofitFee: bigint,
    netAmount: bigint,
    timestamp: bigint,
    displayName: string,
    message: string
  ] & {
    donor: string;
    amount: bigint;
    platformFee: bigint;
    nonprofitFee: bigint;
    netAmount: bigint;
    timestamp: bigint;
    displayName: string;
    message: string;
  };
}

export interface PatriotPledgeNFTV9Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "GIFT_NONPROFIT_FEE_BPS"
      | "GIFT_PLATFORM_FEE_BPS"
      | "MAX_BATCH_SIZE"
      | "MAX_FEE_BPS"
      | "VERSION"
      | "approve"
      | "balanceOf"
      | "blacklistAddress"
      | "blacklisted"
      | "campaignDistributed"
      | "campaignGiftBalance"
      | "campaignGiftCount"
      | "campaignGifts"
      | "campaignGiftsDistributed"
      | "campaigns"
      | "closeCampaign"
      | "createCampaign"
      | "deploymentChainId"
      | "distributeGifts"
      | "distributePendingFunds"
      | "emergencyWithdraw"
      | "frozenTokens"
      | "getApproved"
      | "getCampaign"
      | "getGiftBalance"
      | "getGiftCount"
      | "getGiftHistory"
      | "giveGift"
      | "giveGiftWithMessage"
      | "isApprovedForAll"
      | "mint"
      | "mintWithGift"
      | "name"
      | "owner"
      | "ownerOf"
      | "pause"
      | "pauseCampaign"
      | "paused"
      | "platformFeeBps"
      | "platformTreasury"
      | "renounceOwnership"
      | "royaltyInfo"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setImmediatePayoutEnabled"
      | "setPlatformFeeBps"
      | "setPlatformTreasury"
      | "soulbound"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenEditionNumber"
      | "tokenOfOwnerByIndex"
      | "tokenToCampaign"
      | "tokenURI"
      | "totalCampaigns"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "CampaignClosed"
      | "CampaignCreated"
      | "CampaignPaused"
      | "EditionMinted"
      | "FundsDistributed"
      | "GiftReceived"
      | "GiftsDistributed"
      | "MetadataUpdate"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformFeeUpdated"
      | "PlatformTreasuryUpdated"
      | "Transfer"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GIFT_NONPROFIT_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GIFT_PLATFORM_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistAddress",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignDistributed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignGiftBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignGiftCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignGifts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignGiftsDistributed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributeGifts",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePendingFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "frozenTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGiftBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGiftCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGiftHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveGift",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "giveGiftWithMessage",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "mint", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "mintWithGift",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseCampaign",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setImmediatePayoutEnabled",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "soulbound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenEditionNumber",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GIFT_NONPROFIT_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GIFT_PLATFORM_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignGiftBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignGiftCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignGifts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignGiftsDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeGifts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePendingFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frozenTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGiftBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGiftCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGiftHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "giveGift", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "giveGiftWithMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintWithGift",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImmediatePayoutEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "soulbound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenEditionNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignClosedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    nonprofit: AddressLike,
    submitter: AddressLike,
    category: string,
    goalNative: BigNumberish,
    goalUsd: BigNumberish,
    maxEditions: BigNumberish,
    priceNative: BigNumberish,
    priceUsd: BigNumberish,
    immediatePayoutEnabled: boolean
  ];
  export type OutputTuple = [
    campaignId: bigint,
    nonprofit: string,
    submitter: string,
    category: string,
    goalNative: bigint,
    goalUsd: bigint,
    maxEditions: bigint,
    priceNative: bigint,
    priceUsd: bigint,
    immediatePayoutEnabled: boolean
  ];
  export interface OutputObject {
    campaignId: bigint;
    nonprofit: string;
    submitter: string;
    category: string;
    goalNative: bigint;
    goalUsd: bigint;
    maxEditions: bigint;
    priceNative: bigint;
    priceUsd: bigint;
    immediatePayoutEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignPausedEvent {
  export type InputTuple = [campaignId: BigNumberish, paused: boolean];
  export type OutputTuple = [campaignId: bigint, paused: boolean];
  export interface OutputObject {
    campaignId: bigint;
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EditionMintedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    tokenId: BigNumberish,
    donor: AddressLike,
    editionNumber: BigNumberish,
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    tokenId: bigint,
    donor: string,
    editionNumber: bigint,
    amountPaid: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    tokenId: bigint;
    donor: string;
    editionNumber: bigint;
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDistributedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    platformFee: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    recipient: string,
    amount: bigint,
    platformFee: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    recipient: string;
    amount: bigint;
    platformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiftReceivedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    donor: AddressLike,
    totalAmount: BigNumberish,
    platformFee: BigNumberish,
    nonprofitFee: BigNumberish,
    netAmount: BigNumberish,
    displayName: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    donor: string,
    totalAmount: bigint,
    platformFee: bigint,
    nonprofitFee: bigint,
    netAmount: bigint,
    displayName: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    donor: string;
    totalAmount: bigint;
    platformFee: bigint;
    nonprofitFee: bigint;
    netAmount: bigint;
    displayName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GiftsDistributedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    toSubmitter: BigNumberish,
    toPlatform: BigNumberish,
    submitterPercent: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    toSubmitter: bigint,
    toPlatform: bigint,
    submitterPercent: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    toSubmitter: bigint;
    toPlatform: bigint;
    submitterPercent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformTreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatriotPledgeNFTV9 extends BaseContract {
  connect(runner?: ContractRunner | null): PatriotPledgeNFTV9;
  waitForDeployment(): Promise<this>;

  interface: PatriotPledgeNFTV9Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  GIFT_NONPROFIT_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  GIFT_PLATFORM_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [bigint], "view">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  blacklistAddress: TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  blacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  campaignDistributed: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  campaignGiftBalance: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  campaignGiftCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  campaignGifts: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, string, string] & {
        donor: string;
        amount: bigint;
        platformFee: bigint;
        nonprofitFee: bigint;
        netAmount: bigint;
        timestamp: bigint;
        displayName: string;
        message: string;
      }
    ],
    "view"
  >;

  campaignGiftsDistributed: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        category: string;
        baseURI: string;
        goalNative: bigint;
        goalUsd: bigint;
        grossRaised: bigint;
        netRaised: bigint;
        giftsReceived: bigint;
        editionsMinted: bigint;
        maxEditions: bigint;
        priceNative: bigint;
        priceUsd: bigint;
        nonprofit: string;
        submitter: string;
        active: boolean;
        paused: boolean;
        closed: boolean;
        refunded: boolean;
        immediatePayoutEnabled: boolean;
      }
    ],
    "view"
  >;

  closeCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      category: string,
      uri: string,
      goalNative: BigNumberish,
      goalUsd: BigNumberish,
      maxEditions: BigNumberish,
      priceNative: BigNumberish,
      priceUsd: BigNumberish,
      nonprofit: AddressLike,
      submitter: AddressLike,
      immediatePayoutEnabled: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  deploymentChainId: TypedContractMethod<[], [bigint], "view">;

  distributeGifts: TypedContractMethod<
    [campaignId: BigNumberish, submitterPercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributePendingFunds: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  frozenTokens: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [PatriotPledgeNFTV9.CampaignViewStructOutput],
    "view"
  >;

  getGiftBalance: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  getGiftCount: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "view"
  >;

  getGiftHistory: TypedContractMethod<
    [campaignId: BigNumberish],
    [PatriotPledgeNFTV9.GiftStructOutput[]],
    "view"
  >;

  giveGift: TypedContractMethod<[campaignId: BigNumberish], [void], "payable">;

  giveGiftWithMessage: TypedContractMethod<
    [campaignId: BigNumberish, displayName: string, message: string],
    [void],
    "payable"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  mint: TypedContractMethod<[campaignId: BigNumberish], [bigint], "payable">;

  mintWithGift: TypedContractMethod<
    [campaignId: BigNumberish, giftAmount: BigNumberish],
    [bigint],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauseCampaign: TypedContractMethod<
    [campaignId: BigNumberish, paused: boolean],
    [void],
    "nonpayable"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  royaltyInfo: TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint] & { receiver: string; amount: bigint }],
    "view"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setImmediatePayoutEnabled: TypedContractMethod<
    [campaignId: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformFeeBps: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  soulbound: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenEditionNumber: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenToCampaign: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalCampaigns: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GIFT_NONPROFIT_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GIFT_PLATFORM_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "blacklistAddress"
  ): TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "campaignDistributed"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignGiftBalance"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignGiftCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignGifts"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, bigint, string, string] & {
        donor: string;
        amount: bigint;
        platformFee: bigint;
        nonprofitFee: bigint;
        netAmount: bigint;
        timestamp: bigint;
        displayName: string;
        message: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaignGiftsDistributed"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        category: string;
        baseURI: string;
        goalNative: bigint;
        goalUsd: bigint;
        grossRaised: bigint;
        netRaised: bigint;
        giftsReceived: bigint;
        editionsMinted: bigint;
        maxEditions: bigint;
        priceNative: bigint;
        priceUsd: bigint;
        nonprofit: string;
        submitter: string;
        active: boolean;
        paused: boolean;
        closed: boolean;
        refunded: boolean;
        immediatePayoutEnabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      category: string,
      uri: string,
      goalNative: BigNumberish,
      goalUsd: BigNumberish,
      maxEditions: BigNumberish,
      priceNative: BigNumberish,
      priceUsd: BigNumberish,
      nonprofit: AddressLike,
      submitter: AddressLike,
      immediatePayoutEnabled: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deploymentChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeGifts"
  ): TypedContractMethod<
    [campaignId: BigNumberish, submitterPercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributePendingFunds"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "frozenTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [PatriotPledgeNFTV9.CampaignViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGiftBalance"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGiftCount"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGiftHistory"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [PatriotPledgeNFTV9.GiftStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "giveGift"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "giveGiftWithMessage"
  ): TypedContractMethod<
    [campaignId: BigNumberish, displayName: string, message: string],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "mintWithGift"
  ): TypedContractMethod<
    [campaignId: BigNumberish, giftAmount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauseCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish, paused: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "royaltyInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint] & { receiver: string; amount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setImmediatePayoutEnabled"
  ): TypedContractMethod<
    [campaignId: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFeeBps"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "soulbound"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenEditionNumber"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenToCampaign"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalCampaigns"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "CampaignClosed"
  ): TypedContractEvent<
    CampaignClosedEvent.InputTuple,
    CampaignClosedEvent.OutputTuple,
    CampaignClosedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignPaused"
  ): TypedContractEvent<
    CampaignPausedEvent.InputTuple,
    CampaignPausedEvent.OutputTuple,
    CampaignPausedEvent.OutputObject
  >;
  getEvent(
    key: "EditionMinted"
  ): TypedContractEvent<
    EditionMintedEvent.InputTuple,
    EditionMintedEvent.OutputTuple,
    EditionMintedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDistributed"
  ): TypedContractEvent<
    FundsDistributedEvent.InputTuple,
    FundsDistributedEvent.OutputTuple,
    FundsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "GiftReceived"
  ): TypedContractEvent<
    GiftReceivedEvent.InputTuple,
    GiftReceivedEvent.OutputTuple,
    GiftReceivedEvent.OutputObject
  >;
  getEvent(
    key: "GiftsDistributed"
  ): TypedContractEvent<
    GiftsDistributedEvent.InputTuple,
    GiftsDistributedEvent.OutputTuple,
    GiftsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformTreasuryUpdated"
  ): TypedContractEvent<
    PlatformTreasuryUpdatedEvent.InputTuple,
    PlatformTreasuryUpdatedEvent.OutputTuple,
    PlatformTreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "CampaignClosed(uint256)": TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;
    CampaignClosed: TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address,string,uint256,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignPaused(uint256,bool)": TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;
    CampaignPaused: TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;

    "EditionMinted(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      EditionMintedEvent.InputTuple,
      EditionMintedEvent.OutputTuple,
      EditionMintedEvent.OutputObject
    >;
    EditionMinted: TypedContractEvent<
      EditionMintedEvent.InputTuple,
      EditionMintedEvent.OutputTuple,
      EditionMintedEvent.OutputObject
    >;

    "FundsDistributed(uint256,address,uint256,uint256)": TypedContractEvent<
      FundsDistributedEvent.InputTuple,
      FundsDistributedEvent.OutputTuple,
      FundsDistributedEvent.OutputObject
    >;
    FundsDistributed: TypedContractEvent<
      FundsDistributedEvent.InputTuple,
      FundsDistributedEvent.OutputTuple,
      FundsDistributedEvent.OutputObject
    >;

    "GiftReceived(uint256,address,uint256,uint256,uint256,uint256,string)": TypedContractEvent<
      GiftReceivedEvent.InputTuple,
      GiftReceivedEvent.OutputTuple,
      GiftReceivedEvent.OutputObject
    >;
    GiftReceived: TypedContractEvent<
      GiftReceivedEvent.InputTuple,
      GiftReceivedEvent.OutputTuple,
      GiftReceivedEvent.OutputObject
    >;

    "GiftsDistributed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      GiftsDistributedEvent.InputTuple,
      GiftsDistributedEvent.OutputTuple,
      GiftsDistributedEvent.OutputObject
    >;
    GiftsDistributed: TypedContractEvent<
      GiftsDistributedEvent.InputTuple,
      GiftsDistributedEvent.OutputTuple,
      GiftsDistributedEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint16,uint16)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "PlatformTreasuryUpdated(address,address)": TypedContractEvent<
      PlatformTreasuryUpdatedEvent.InputTuple,
      PlatformTreasuryUpdatedEvent.OutputTuple,
      PlatformTreasuryUpdatedEvent.OutputObject
    >;
    PlatformTreasuryUpdated: TypedContractEvent<
      PlatformTreasuryUpdatedEvent.InputTuple,
      PlatformTreasuryUpdatedEvent.OutputTuple,
      PlatformTreasuryUpdatedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
