/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PatriotPledgeNFTV7Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_BATCH_SIZE"
      | "MAX_FEE_BPS"
      | "adminBurn"
      | "approve"
      | "balanceOf"
      | "batchFixTokenCampaignLink"
      | "batchFreezeTokens"
      | "batchSetTokenURI"
      | "blacklistAddress"
      | "blacklisted"
      | "bugBountyPool"
      | "burn"
      | "campaignDistributed"
      | "campaignEditions"
      | "campaigns"
      | "closeCampaign"
      | "createCampaign"
      | "deactivateCampaign"
      | "defaultRoyaltyBps"
      | "deleteDefaultRoyalty"
      | "deploymentChainId"
      | "distributePendingFunds"
      | "emergencyWithdraw"
      | "emitBatchMetadataUpdate"
      | "emitMetadataUpdate"
      | "feeConfig"
      | "fixTokenCampaignLink"
      | "freezeToken"
      | "frozenTokens"
      | "fundBugBountyPool"
      | "getApproved"
      | "getCampaign"
      | "getCampaignEditions"
      | "getEditionInfo"
      | "getFeeConfig"
      | "isApprovedForAll"
      | "makeSoulbound"
      | "markCampaignRefunded"
      | "mintBatchWithBDAG"
      | "mintBatchWithBDAGAndTip"
      | "mintBatchWithImmediatePayout"
      | "mintBatchWithImmediatePayoutAndTip"
      | "mintEditionToDonor"
      | "mintWithBDAG"
      | "mintWithBDAGAndTip"
      | "mintWithImmediatePayout"
      | "mintWithImmediatePayoutAndTip"
      | "name"
      | "owner"
      | "ownerOf"
      | "pause"
      | "paused"
      | "payBugBounty"
      | "platformTreasury"
      | "reactivateCampaign"
      | "recordContribution"
      | "removeBlacklist"
      | "removeSoulbound"
      | "renounceOwnership"
      | "royaltyInfo"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "setCampaignImmediatePayout"
      | "setDefaultRoyalty"
      | "setFeeConfig"
      | "setPlatformTreasury"
      | "setTokenRoyalty"
      | "setTokenURI"
      | "soulbound"
      | "supportsInterface"
      | "symbol"
      | "tokenByIndex"
      | "tokenEditionNumber"
      | "tokenOfOwnerByIndex"
      | "tokenToCampaign"
      | "tokenURI"
      | "totalCampaigns"
      | "totalSupply"
      | "transferFrom"
      | "transferOwnership"
      | "unfreezeToken"
      | "unpause"
      | "updateCampaignCategory"
      | "updateCampaignGoal"
      | "updateCampaignMaxEditions"
      | "updateCampaignMetadata"
      | "updateCampaignNonprofit"
      | "updateCampaignPrice"
      | "updateCampaignSubmitter"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressBlacklisted"
      | "Approval"
      | "ApprovalForAll"
      | "BatchMetadataUpdate"
      | "BugBountyFunded"
      | "BugBountyPaid"
      | "CampaignClosed"
      | "CampaignCreated"
      | "CampaignMetadataUpdated"
      | "CampaignRefunded"
      | "CampaignUpdated"
      | "ContributionRecorded"
      | "DefaultRoyaltyUpdated"
      | "EditionMinted"
      | "EmergencyWithdraw"
      | "FeeConfigUpdated"
      | "FundsDistributed"
      | "ImmediatePayoutSent"
      | "MetadataUpdate"
      | "OwnershipTransferred"
      | "Paused"
      | "TokenBurned"
      | "TokenFrozen"
      | "TokenSoulbound"
      | "TokenURIFixed"
      | "Transfer"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminBurn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchFixTokenCampaignLink",
    values: [BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchFreezeTokens",
    values: [BigNumberish[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetTokenURI",
    values: [BigNumberish[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bugBountyPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "burn", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "campaignDistributed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignEditions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultRoyaltyBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteDefaultRoyalty",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentChainId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distributePendingFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emitBatchMetadataUpdate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emitMetadataUpdate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "feeConfig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fixTokenCampaignLink",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "frozenTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundBugBountyPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignEditions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEditionInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "makeSoulbound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markCampaignRefunded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatchWithBDAG",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatchWithBDAGAndTip",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatchWithImmediatePayout",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBatchWithImmediatePayoutAndTip",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintEditionToDonor",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithBDAG",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithBDAGAndTip",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithImmediatePayout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintWithImmediatePayoutAndTip",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payBugBounty",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reactivateCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordContribution",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "removeBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSoulbound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignImmediatePayout",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultRoyalty",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeConfig",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenRoyalty",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "soulbound",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenEditionNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateCampaignCategory",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignGoal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignMaxEditions",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignMetadata",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignNonprofit",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCampaignSubmitter",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "adminBurn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchFixTokenCampaignLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchFreezeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bugBountyPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "campaignDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignEditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultRoyaltyBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteDefaultRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentChainId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePendingFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitBatchMetadataUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emitMetadataUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeConfig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fixTokenCampaignLink",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "frozenTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundBugBountyPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignEditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEditionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeSoulbound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markCampaignRefunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBatchWithBDAG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBatchWithBDAGAndTip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBatchWithImmediatePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBatchWithImmediatePayoutAndTip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintEditionToDonor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintWithBDAG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintWithBDAGAndTip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintWithImmediatePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintWithImmediatePayoutAndTip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payBugBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reactivateCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSoulbound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignImmediatePayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenRoyalty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "soulbound", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenEditionNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenToCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignGoal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignMaxEditions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignNonprofit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCampaignSubmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AddressBlacklistedEvent {
  export type InputTuple = [addr: AddressLike, blacklisted: boolean];
  export type OutputTuple = [addr: string, blacklisted: boolean];
  export interface OutputObject {
    addr: string;
    blacklisted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    approved: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [owner: string, approved: string, tokenId: bigint];
  export interface OutputObject {
    owner: string;
    approved: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalForAllEvent {
  export type InputTuple = [
    owner: AddressLike,
    operator: AddressLike,
    approved: boolean
  ];
  export type OutputTuple = [
    owner: string,
    operator: string,
    approved: boolean
  ];
  export interface OutputObject {
    owner: string;
    operator: string;
    approved: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchMetadataUpdateEvent {
  export type InputTuple = [
    _fromTokenId: BigNumberish,
    _toTokenId: BigNumberish
  ];
  export type OutputTuple = [_fromTokenId: bigint, _toTokenId: bigint];
  export interface OutputObject {
    _fromTokenId: bigint;
    _toTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BugBountyFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BugBountyPaidEvent {
  export type InputTuple = [
    recipient: AddressLike,
    amount: BigNumberish,
    reportId: string
  ];
  export type OutputTuple = [
    recipient: string,
    amount: bigint,
    reportId: string
  ];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
    reportId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignClosedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    nonprofit: AddressLike,
    submitter: AddressLike,
    category: string,
    goal: BigNumberish,
    maxEditions: BigNumberish,
    pricePerEdition: BigNumberish,
    immediatePayoutEnabled: boolean
  ];
  export type OutputTuple = [
    campaignId: bigint,
    nonprofit: string,
    submitter: string,
    category: string,
    goal: bigint,
    maxEditions: bigint,
    pricePerEdition: bigint,
    immediatePayoutEnabled: boolean
  ];
  export interface OutputObject {
    campaignId: bigint;
    nonprofit: string;
    submitter: string;
    category: string;
    goal: bigint;
    maxEditions: bigint;
    pricePerEdition: bigint;
    immediatePayoutEnabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignMetadataUpdatedEvent {
  export type InputTuple = [campaignId: BigNumberish, newBaseURI: string];
  export type OutputTuple = [campaignId: bigint, newBaseURI: string];
  export interface OutputObject {
    campaignId: bigint;
    newBaseURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignRefundedEvent {
  export type InputTuple = [campaignId: BigNumberish];
  export type OutputTuple = [campaignId: bigint];
  export interface OutputObject {
    campaignId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignUpdatedEvent {
  export type InputTuple = [campaignId: BigNumberish, field: string];
  export type OutputTuple = [campaignId: bigint, field: string];
  export interface OutputObject {
    campaignId: bigint;
    field: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContributionRecordedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    gross: BigNumberish,
    net: BigNumberish,
    tip: BigNumberish,
    isOnchain: boolean
  ];
  export type OutputTuple = [
    campaignId: bigint,
    gross: bigint,
    net: bigint,
    tip: bigint,
    isOnchain: boolean
  ];
  export interface OutputObject {
    campaignId: bigint;
    gross: bigint;
    net: bigint;
    tip: bigint;
    isOnchain: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefaultRoyaltyUpdatedEvent {
  export type InputTuple = [newRoyaltyBps: BigNumberish];
  export type OutputTuple = [newRoyaltyBps: bigint];
  export interface OutputObject {
    newRoyaltyBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EditionMintedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    tokenId: BigNumberish,
    donor: AddressLike,
    editionNumber: BigNumberish,
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    tokenId: bigint,
    donor: string,
    editionNumber: bigint,
    amountPaid: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    tokenId: bigint;
    donor: string;
    editionNumber: bigint;
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeConfigUpdatedEvent {
  export type InputTuple = [
    platformFeeBps: BigNumberish,
    immediatePayout: boolean
  ];
  export type OutputTuple = [platformFeeBps: bigint, immediatePayout: boolean];
  export interface OutputObject {
    platformFeeBps: bigint;
    immediatePayout: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsDistributedEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    submitter: AddressLike,
    submitterAmount: BigNumberish,
    platformFee: BigNumberish,
    nonprofitFee: BigNumberish,
    tipAmount: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: bigint,
    submitter: string,
    submitterAmount: bigint,
    platformFee: bigint,
    nonprofitFee: bigint,
    tipAmount: bigint
  ];
  export interface OutputObject {
    campaignId: bigint;
    submitter: string;
    submitterAmount: bigint;
    platformFee: bigint;
    nonprofitFee: bigint;
    tipAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ImmediatePayoutSentEvent {
  export type InputTuple = [
    campaignId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    recipientType: string
  ];
  export type OutputTuple = [
    campaignId: bigint,
    recipient: string,
    amount: bigint,
    recipientType: string
  ];
  export interface OutputObject {
    campaignId: bigint;
    recipient: string;
    amount: bigint;
    recipientType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdateEvent {
  export type InputTuple = [_tokenId: BigNumberish];
  export type OutputTuple = [_tokenId: bigint];
  export interface OutputObject {
    _tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBurnedEvent {
  export type InputTuple = [tokenId: BigNumberish, burner: AddressLike];
  export type OutputTuple = [tokenId: bigint, burner: string];
  export interface OutputObject {
    tokenId: bigint;
    burner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFrozenEvent {
  export type InputTuple = [tokenId: BigNumberish, frozen: boolean];
  export type OutputTuple = [tokenId: bigint, frozen: boolean];
  export interface OutputObject {
    tokenId: bigint;
    frozen: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSoulboundEvent {
  export type InputTuple = [tokenId: BigNumberish, soulbound: boolean];
  export type OutputTuple = [tokenId: bigint, soulbound: boolean];
  export interface OutputObject {
    tokenId: bigint;
    soulbound: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenURIFixedEvent {
  export type InputTuple = [tokenId: BigNumberish, newURI: string];
  export type OutputTuple = [tokenId: bigint, newURI: string];
  export interface OutputObject {
    tokenId: bigint;
    newURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatriotPledgeNFTV7 extends BaseContract {
  connect(runner?: ContractRunner | null): PatriotPledgeNFTV7;
  waitForDeployment(): Promise<this>;

  interface: PatriotPledgeNFTV7Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  adminBurn: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  approve: TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  batchFixTokenCampaignLink: TypedContractMethod<
    [tokenIds: BigNumberish[], campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  batchFreezeTokens: TypedContractMethod<
    [tokenIds: BigNumberish[], freeze: boolean],
    [void],
    "nonpayable"
  >;

  batchSetTokenURI: TypedContractMethod<
    [tokenIds: BigNumberish[], uri: string],
    [void],
    "nonpayable"
  >;

  blacklistAddress: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "nonpayable"
  >;

  blacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  bugBountyPool: TypedContractMethod<[], [bigint], "view">;

  burn: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  campaignDistributed: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  campaignEditions: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        category: string;
        baseURI: string;
        goal: bigint;
        grossRaised: bigint;
        netRaised: bigint;
        tipsReceived: bigint;
        editionsMinted: bigint;
        maxEditions: bigint;
        pricePerEdition: bigint;
        nonprofit: string;
        submitter: string;
        active: boolean;
        closed: boolean;
        refunded: boolean;
        immediatePayoutEnabled: boolean;
      }
    ],
    "view"
  >;

  closeCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createCampaign: TypedContractMethod<
    [
      category: string,
      baseURI: string,
      goal: BigNumberish,
      maxEditions: BigNumberish,
      pricePerEdition: BigNumberish,
      nonprofit: AddressLike,
      submitter: AddressLike,
      immediatePayoutEnabled: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  deactivateCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  defaultRoyaltyBps: TypedContractMethod<[], [bigint], "view">;

  deleteDefaultRoyalty: TypedContractMethod<[], [void], "nonpayable">;

  deploymentChainId: TypedContractMethod<[], [bigint], "view">;

  distributePendingFunds: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  emitBatchMetadataUpdate: TypedContractMethod<
    [fromTokenId: BigNumberish, toTokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emitMetadataUpdate: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeConfig: TypedContractMethod<
    [],
    [[bigint, boolean] & { platformFeeBps: bigint; immediatePayout: boolean }],
    "view"
  >;

  fixTokenCampaignLink: TypedContractMethod<
    [tokenId: BigNumberish, campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  freezeToken: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  frozenTokens: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  fundBugBountyPool: TypedContractMethod<[], [void], "payable">;

  getApproved: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  getCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean
      ] & {
        category: string;
        baseURI: string;
        goal: bigint;
        grossRaised: bigint;
        netRaised: bigint;
        editionsMinted: bigint;
        maxEditions: bigint;
        pricePerEdition: bigint;
        nonprofit: string;
        submitter: string;
        active: boolean;
        closed: boolean;
        immediatePayoutEnabled: boolean;
      }
    ],
    "view"
  >;

  getCampaignEditions: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getEditionInfo: TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        campaignId: bigint;
        editionNumber: bigint;
        totalEditions: bigint;
      }
    ],
    "view"
  >;

  getFeeConfig: TypedContractMethod<
    [],
    [[bigint, boolean] & { platformFeeBps: bigint; immediatePayout: boolean }],
    "view"
  >;

  isApprovedForAll: TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;

  makeSoulbound: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  markCampaignRefunded: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintBatchWithBDAG: TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish],
    [bigint[]],
    "payable"
  >;

  mintBatchWithBDAGAndTip: TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish, tipAmount: BigNumberish],
    [bigint[]],
    "payable"
  >;

  mintBatchWithImmediatePayout: TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish],
    [bigint[]],
    "payable"
  >;

  mintBatchWithImmediatePayoutAndTip: TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish, tipAmount: BigNumberish],
    [bigint[]],
    "payable"
  >;

  mintEditionToDonor: TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike, amountPaid: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  mintWithBDAG: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "payable"
  >;

  mintWithBDAGAndTip: TypedContractMethod<
    [campaignId: BigNumberish, tipAmount: BigNumberish],
    [bigint],
    "payable"
  >;

  mintWithImmediatePayout: TypedContractMethod<
    [campaignId: BigNumberish],
    [bigint],
    "payable"
  >;

  mintWithImmediatePayoutAndTip: TypedContractMethod<
    [campaignId: BigNumberish, tipAmount: BigNumberish],
    [bigint],
    "payable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payBugBounty: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, reportId: string],
    [void],
    "nonpayable"
  >;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  reactivateCampaign: TypedContractMethod<
    [campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordContribution: TypedContractMethod<
    [
      campaignId: BigNumberish,
      gross: BigNumberish,
      net: BigNumberish,
      tip: BigNumberish,
      isOnchain: boolean
    ],
    [void],
    "nonpayable"
  >;

  removeBlacklist: TypedContractMethod<
    [addr: AddressLike],
    [void],
    "nonpayable"
  >;

  removeSoulbound: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  royaltyInfo: TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  "safeTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "safeTransferFrom(address,address,uint256,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setApprovalForAll: TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;

  setCampaignImmediatePayout: TypedContractMethod<
    [campaignId: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setDefaultRoyalty: TypedContractMethod<
    [receiver: AddressLike, feeNumerator: BigNumberish],
    [void],
    "nonpayable"
  >;

  setFeeConfig: TypedContractMethod<
    [_platformFeeBps: BigNumberish, _immediatePayout: boolean],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenRoyalty: TypedContractMethod<
    [tokenId: BigNumberish, receiver: AddressLike, feeNumerator: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenURI: TypedContractMethod<
    [tokenId: BigNumberish, uri: string],
    [void],
    "nonpayable"
  >;

  soulbound: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  tokenByIndex: TypedContractMethod<[index: BigNumberish], [bigint], "view">;

  tokenEditionNumber: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenToCampaign: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalCampaigns: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unfreezeToken: TypedContractMethod<
    [tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateCampaignCategory: TypedContractMethod<
    [campaignId: BigNumberish, newCategory: string],
    [void],
    "nonpayable"
  >;

  updateCampaignGoal: TypedContractMethod<
    [campaignId: BigNumberish, newGoal: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateCampaignMaxEditions: TypedContractMethod<
    [campaignId: BigNumberish, newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateCampaignMetadata: TypedContractMethod<
    [campaignId: BigNumberish, newBaseURI: string],
    [void],
    "nonpayable"
  >;

  updateCampaignNonprofit: TypedContractMethod<
    [campaignId: BigNumberish, newNonprofit: AddressLike],
    [void],
    "nonpayable"
  >;

  updateCampaignPrice: TypedContractMethod<
    [campaignId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateCampaignSubmitter: TypedContractMethod<
    [campaignId: BigNumberish, newSubmitter: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminBurn"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchFixTokenCampaignLink"
  ): TypedContractMethod<
    [tokenIds: BigNumberish[], campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchFreezeTokens"
  ): TypedContractMethod<
    [tokenIds: BigNumberish[], freeze: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSetTokenURI"
  ): TypedContractMethod<
    [tokenIds: BigNumberish[], uri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "blacklistAddress"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "bugBountyPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "campaignDistributed"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignEditions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean,
        boolean
      ] & {
        category: string;
        baseURI: string;
        goal: bigint;
        grossRaised: bigint;
        netRaised: bigint;
        tipsReceived: bigint;
        editionsMinted: bigint;
        maxEditions: bigint;
        pricePerEdition: bigint;
        nonprofit: string;
        submitter: string;
        active: boolean;
        closed: boolean;
        refunded: boolean;
        immediatePayoutEnabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      category: string,
      baseURI: string,
      goal: BigNumberish,
      maxEditions: BigNumberish,
      pricePerEdition: BigNumberish,
      nonprofit: AddressLike,
      submitter: AddressLike,
      immediatePayoutEnabled: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultRoyaltyBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deleteDefaultRoyalty"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deploymentChainId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributePendingFunds"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emitBatchMetadataUpdate"
  ): TypedContractMethod<
    [fromTokenId: BigNumberish, toTokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emitMetadataUpdate"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeConfig"
  ): TypedContractMethod<
    [],
    [[bigint, boolean] & { platformFeeBps: bigint; immediatePayout: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "fixTokenCampaignLink"
  ): TypedContractMethod<
    [tokenId: BigNumberish, campaignId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezeToken"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "frozenTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "fundBugBountyPool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getApproved"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getCampaign"
  ): TypedContractMethod<
    [campaignId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        boolean,
        boolean
      ] & {
        category: string;
        baseURI: string;
        goal: bigint;
        grossRaised: bigint;
        netRaised: bigint;
        editionsMinted: bigint;
        maxEditions: bigint;
        pricePerEdition: bigint;
        nonprofit: string;
        submitter: string;
        active: boolean;
        closed: boolean;
        immediatePayoutEnabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignEditions"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getEditionInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        campaignId: bigint;
        editionNumber: bigint;
        totalEditions: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeeConfig"
  ): TypedContractMethod<
    [],
    [[bigint, boolean] & { platformFeeBps: bigint; immediatePayout: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isApprovedForAll"
  ): TypedContractMethod<
    [owner: AddressLike, operator: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "makeSoulbound"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markCampaignRefunded"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintBatchWithBDAG"
  ): TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintBatchWithBDAGAndTip"
  ): TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish, tipAmount: BigNumberish],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintBatchWithImmediatePayout"
  ): TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintBatchWithImmediatePayoutAndTip"
  ): TypedContractMethod<
    [campaignId: BigNumberish, quantity: BigNumberish, tipAmount: BigNumberish],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintEditionToDonor"
  ): TypedContractMethod<
    [campaignId: BigNumberish, donor: AddressLike, amountPaid: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintWithBDAG"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "mintWithBDAGAndTip"
  ): TypedContractMethod<
    [campaignId: BigNumberish, tipAmount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "mintWithImmediatePayout"
  ): TypedContractMethod<[campaignId: BigNumberish], [bigint], "payable">;
  getFunction(
    nameOrSignature: "mintWithImmediatePayoutAndTip"
  ): TypedContractMethod<
    [campaignId: BigNumberish, tipAmount: BigNumberish],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payBugBounty"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish, reportId: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactivateCampaign"
  ): TypedContractMethod<[campaignId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordContribution"
  ): TypedContractMethod<
    [
      campaignId: BigNumberish,
      gross: BigNumberish,
      net: BigNumberish,
      tip: BigNumberish,
      isOnchain: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeBlacklist"
  ): TypedContractMethod<[addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSoulbound"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "royaltyInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "safeTransferFrom(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      tokenId: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setApprovalForAll"
  ): TypedContractMethod<
    [operator: AddressLike, approved: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCampaignImmediatePayout"
  ): TypedContractMethod<
    [campaignId: BigNumberish, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultRoyalty"
  ): TypedContractMethod<
    [receiver: AddressLike, feeNumerator: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFeeConfig"
  ): TypedContractMethod<
    [_platformFeeBps: BigNumberish, _immediatePayout: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenRoyalty"
  ): TypedContractMethod<
    [tokenId: BigNumberish, receiver: AddressLike, feeNumerator: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenURI"
  ): TypedContractMethod<
    [tokenId: BigNumberish, uri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "soulbound"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenByIndex"
  ): TypedContractMethod<[index: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenEditionNumber"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenToCampaign"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalCampaigns"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unfreezeToken"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateCampaignCategory"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newCategory: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignGoal"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newGoal: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignMaxEditions"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newMax: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignMetadata"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newBaseURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignNonprofit"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newNonprofit: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignPrice"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCampaignSubmitter"
  ): TypedContractMethod<
    [campaignId: BigNumberish, newSubmitter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddressBlacklisted"
  ): TypedContractEvent<
    AddressBlacklistedEvent.InputTuple,
    AddressBlacklistedEvent.OutputTuple,
    AddressBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ApprovalForAll"
  ): TypedContractEvent<
    ApprovalForAllEvent.InputTuple,
    ApprovalForAllEvent.OutputTuple,
    ApprovalForAllEvent.OutputObject
  >;
  getEvent(
    key: "BatchMetadataUpdate"
  ): TypedContractEvent<
    BatchMetadataUpdateEvent.InputTuple,
    BatchMetadataUpdateEvent.OutputTuple,
    BatchMetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "BugBountyFunded"
  ): TypedContractEvent<
    BugBountyFundedEvent.InputTuple,
    BugBountyFundedEvent.OutputTuple,
    BugBountyFundedEvent.OutputObject
  >;
  getEvent(
    key: "BugBountyPaid"
  ): TypedContractEvent<
    BugBountyPaidEvent.InputTuple,
    BugBountyPaidEvent.OutputTuple,
    BugBountyPaidEvent.OutputObject
  >;
  getEvent(
    key: "CampaignClosed"
  ): TypedContractEvent<
    CampaignClosedEvent.InputTuple,
    CampaignClosedEvent.OutputTuple,
    CampaignClosedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignMetadataUpdated"
  ): TypedContractEvent<
    CampaignMetadataUpdatedEvent.InputTuple,
    CampaignMetadataUpdatedEvent.OutputTuple,
    CampaignMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignRefunded"
  ): TypedContractEvent<
    CampaignRefundedEvent.InputTuple,
    CampaignRefundedEvent.OutputTuple,
    CampaignRefundedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignUpdated"
  ): TypedContractEvent<
    CampaignUpdatedEvent.InputTuple,
    CampaignUpdatedEvent.OutputTuple,
    CampaignUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContributionRecorded"
  ): TypedContractEvent<
    ContributionRecordedEvent.InputTuple,
    ContributionRecordedEvent.OutputTuple,
    ContributionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DefaultRoyaltyUpdated"
  ): TypedContractEvent<
    DefaultRoyaltyUpdatedEvent.InputTuple,
    DefaultRoyaltyUpdatedEvent.OutputTuple,
    DefaultRoyaltyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EditionMinted"
  ): TypedContractEvent<
    EditionMintedEvent.InputTuple,
    EditionMintedEvent.OutputTuple,
    EditionMintedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "FeeConfigUpdated"
  ): TypedContractEvent<
    FeeConfigUpdatedEvent.InputTuple,
    FeeConfigUpdatedEvent.OutputTuple,
    FeeConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsDistributed"
  ): TypedContractEvent<
    FundsDistributedEvent.InputTuple,
    FundsDistributedEvent.OutputTuple,
    FundsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "ImmediatePayoutSent"
  ): TypedContractEvent<
    ImmediatePayoutSentEvent.InputTuple,
    ImmediatePayoutSentEvent.OutputTuple,
    ImmediatePayoutSentEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdate"
  ): TypedContractEvent<
    MetadataUpdateEvent.InputTuple,
    MetadataUpdateEvent.OutputTuple,
    MetadataUpdateEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TokenBurned"
  ): TypedContractEvent<
    TokenBurnedEvent.InputTuple,
    TokenBurnedEvent.OutputTuple,
    TokenBurnedEvent.OutputObject
  >;
  getEvent(
    key: "TokenFrozen"
  ): TypedContractEvent<
    TokenFrozenEvent.InputTuple,
    TokenFrozenEvent.OutputTuple,
    TokenFrozenEvent.OutputObject
  >;
  getEvent(
    key: "TokenSoulbound"
  ): TypedContractEvent<
    TokenSoulboundEvent.InputTuple,
    TokenSoulboundEvent.OutputTuple,
    TokenSoulboundEvent.OutputObject
  >;
  getEvent(
    key: "TokenURIFixed"
  ): TypedContractEvent<
    TokenURIFixedEvent.InputTuple,
    TokenURIFixedEvent.OutputTuple,
    TokenURIFixedEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AddressBlacklisted(address,bool)": TypedContractEvent<
      AddressBlacklistedEvent.InputTuple,
      AddressBlacklistedEvent.OutputTuple,
      AddressBlacklistedEvent.OutputObject
    >;
    AddressBlacklisted: TypedContractEvent<
      AddressBlacklistedEvent.InputTuple,
      AddressBlacklistedEvent.OutputTuple,
      AddressBlacklistedEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ApprovalForAll(address,address,bool)": TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;
    ApprovalForAll: TypedContractEvent<
      ApprovalForAllEvent.InputTuple,
      ApprovalForAllEvent.OutputTuple,
      ApprovalForAllEvent.OutputObject
    >;

    "BatchMetadataUpdate(uint256,uint256)": TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;
    BatchMetadataUpdate: TypedContractEvent<
      BatchMetadataUpdateEvent.InputTuple,
      BatchMetadataUpdateEvent.OutputTuple,
      BatchMetadataUpdateEvent.OutputObject
    >;

    "BugBountyFunded(address,uint256)": TypedContractEvent<
      BugBountyFundedEvent.InputTuple,
      BugBountyFundedEvent.OutputTuple,
      BugBountyFundedEvent.OutputObject
    >;
    BugBountyFunded: TypedContractEvent<
      BugBountyFundedEvent.InputTuple,
      BugBountyFundedEvent.OutputTuple,
      BugBountyFundedEvent.OutputObject
    >;

    "BugBountyPaid(address,uint256,string)": TypedContractEvent<
      BugBountyPaidEvent.InputTuple,
      BugBountyPaidEvent.OutputTuple,
      BugBountyPaidEvent.OutputObject
    >;
    BugBountyPaid: TypedContractEvent<
      BugBountyPaidEvent.InputTuple,
      BugBountyPaidEvent.OutputTuple,
      BugBountyPaidEvent.OutputObject
    >;

    "CampaignClosed(uint256)": TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;
    CampaignClosed: TypedContractEvent<
      CampaignClosedEvent.InputTuple,
      CampaignClosedEvent.OutputTuple,
      CampaignClosedEvent.OutputObject
    >;

    "CampaignCreated(uint256,address,address,string,uint256,uint256,uint256,bool)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "CampaignMetadataUpdated(uint256,string)": TypedContractEvent<
      CampaignMetadataUpdatedEvent.InputTuple,
      CampaignMetadataUpdatedEvent.OutputTuple,
      CampaignMetadataUpdatedEvent.OutputObject
    >;
    CampaignMetadataUpdated: TypedContractEvent<
      CampaignMetadataUpdatedEvent.InputTuple,
      CampaignMetadataUpdatedEvent.OutputTuple,
      CampaignMetadataUpdatedEvent.OutputObject
    >;

    "CampaignRefunded(uint256)": TypedContractEvent<
      CampaignRefundedEvent.InputTuple,
      CampaignRefundedEvent.OutputTuple,
      CampaignRefundedEvent.OutputObject
    >;
    CampaignRefunded: TypedContractEvent<
      CampaignRefundedEvent.InputTuple,
      CampaignRefundedEvent.OutputTuple,
      CampaignRefundedEvent.OutputObject
    >;

    "CampaignUpdated(uint256,string)": TypedContractEvent<
      CampaignUpdatedEvent.InputTuple,
      CampaignUpdatedEvent.OutputTuple,
      CampaignUpdatedEvent.OutputObject
    >;
    CampaignUpdated: TypedContractEvent<
      CampaignUpdatedEvent.InputTuple,
      CampaignUpdatedEvent.OutputTuple,
      CampaignUpdatedEvent.OutputObject
    >;

    "ContributionRecorded(uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;
    ContributionRecorded: TypedContractEvent<
      ContributionRecordedEvent.InputTuple,
      ContributionRecordedEvent.OutputTuple,
      ContributionRecordedEvent.OutputObject
    >;

    "DefaultRoyaltyUpdated(uint96)": TypedContractEvent<
      DefaultRoyaltyUpdatedEvent.InputTuple,
      DefaultRoyaltyUpdatedEvent.OutputTuple,
      DefaultRoyaltyUpdatedEvent.OutputObject
    >;
    DefaultRoyaltyUpdated: TypedContractEvent<
      DefaultRoyaltyUpdatedEvent.InputTuple,
      DefaultRoyaltyUpdatedEvent.OutputTuple,
      DefaultRoyaltyUpdatedEvent.OutputObject
    >;

    "EditionMinted(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      EditionMintedEvent.InputTuple,
      EditionMintedEvent.OutputTuple,
      EditionMintedEvent.OutputObject
    >;
    EditionMinted: TypedContractEvent<
      EditionMintedEvent.InputTuple,
      EditionMintedEvent.OutputTuple,
      EditionMintedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "FeeConfigUpdated(uint16,bool)": TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;
    FeeConfigUpdated: TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;

    "FundsDistributed(uint256,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      FundsDistributedEvent.InputTuple,
      FundsDistributedEvent.OutputTuple,
      FundsDistributedEvent.OutputObject
    >;
    FundsDistributed: TypedContractEvent<
      FundsDistributedEvent.InputTuple,
      FundsDistributedEvent.OutputTuple,
      FundsDistributedEvent.OutputObject
    >;

    "ImmediatePayoutSent(uint256,address,uint256,string)": TypedContractEvent<
      ImmediatePayoutSentEvent.InputTuple,
      ImmediatePayoutSentEvent.OutputTuple,
      ImmediatePayoutSentEvent.OutputObject
    >;
    ImmediatePayoutSent: TypedContractEvent<
      ImmediatePayoutSentEvent.InputTuple,
      ImmediatePayoutSentEvent.OutputTuple,
      ImmediatePayoutSentEvent.OutputObject
    >;

    "MetadataUpdate(uint256)": TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;
    MetadataUpdate: TypedContractEvent<
      MetadataUpdateEvent.InputTuple,
      MetadataUpdateEvent.OutputTuple,
      MetadataUpdateEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TokenBurned(uint256,address)": TypedContractEvent<
      TokenBurnedEvent.InputTuple,
      TokenBurnedEvent.OutputTuple,
      TokenBurnedEvent.OutputObject
    >;
    TokenBurned: TypedContractEvent<
      TokenBurnedEvent.InputTuple,
      TokenBurnedEvent.OutputTuple,
      TokenBurnedEvent.OutputObject
    >;

    "TokenFrozen(uint256,bool)": TypedContractEvent<
      TokenFrozenEvent.InputTuple,
      TokenFrozenEvent.OutputTuple,
      TokenFrozenEvent.OutputObject
    >;
    TokenFrozen: TypedContractEvent<
      TokenFrozenEvent.InputTuple,
      TokenFrozenEvent.OutputTuple,
      TokenFrozenEvent.OutputObject
    >;

    "TokenSoulbound(uint256,bool)": TypedContractEvent<
      TokenSoulboundEvent.InputTuple,
      TokenSoulboundEvent.OutputTuple,
      TokenSoulboundEvent.OutputObject
    >;
    TokenSoulbound: TypedContractEvent<
      TokenSoulboundEvent.InputTuple,
      TokenSoulboundEvent.OutputTuple,
      TokenSoulboundEvent.OutputObject
    >;

    "TokenURIFixed(uint256,string)": TypedContractEvent<
      TokenURIFixedEvent.InputTuple,
      TokenURIFixedEvent.OutputTuple,
      TokenURIFixedEvent.OutputObject
    >;
    TokenURIFixed: TypedContractEvent<
      TokenURIFixedEvent.InputTuple,
      TokenURIFixedEvent.OutputTuple,
      TokenURIFixedEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
